fix(build/xspdb): add required filelist arg for new picker (#6523)
With new picker, xspdb build fails with:

```
Fatal: Failed to parse RTL sources with slang:
difftest/src/test/vsrc/common/DifftestClockGate.v:17:10: error: 'DifftestMacros.svh': No such file or directory
`include "DifftestMacros.svh"
         ^~~~~~~~~~~~~~~~~~~~
```

due to the refactored filelist parsing and handling.

This PR adds the required arg and prepare for picker/verilator version
bump.

Link: https://github.com/XS-MLVP/picker/pull/103

Signed-off-by: ngc7331 <ngc7331@outlook.com>